# Generated by Django 3.2.6 on 2021-10-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.TextField()),
                ('civ_id', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ranked', models.BooleanField()),
                ('gamemode_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('map_id', models.IntegerField()),
                ('gamecount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('last_pull', models.DateTimeField(blank=True, null=True)),
                ('support_mail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('player_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('winner', models.BooleanField(null=True)),
                ('match_id', models.IntegerField()),
                ('duration', models.DurationField()),
                ('avgelo', models.IntegerField()),
                ('version', models.IntegerField()),
                ('civ1',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civ1', to='game.civ')),
                ('civ2',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civ2', to='game.civ')),
                ('maptype',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='game.map')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1',
                                              to='game.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2',
                                              to='game.player')),
            ],
        ),
    ]
