# Generated by Django 3.2.8 on 2021-11-20 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_metadata_last_pull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='last_pull',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 20, 36, 40, 466678)),
        ),
    ]
